name: Format and Lint Python
on:
    push:
        paths:
            - 'aws_account/**'
            - '.github/**'
    pull-request:
        paths:
            - 'aws_account/**'
            - '.github/**'

jobs:
    lint-python:
        name: "Lint (flake8 & black)"
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'
                  architecture: 'x64'
            - name: List current working dir (debug)
              run: ls -la
            - name: Install Python Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Check Formatting (black)
              run: black --line-length 120 aws_account
            - name: Lint (flake8)
              run: |
                flake8 aws_account
