name: Python Linting
on:
    push:
        paths:
            - 'aws_account/**'
            - '.github/**'
    pull_request:
        paths:
            - 'aws_account/**'
            - '.github/**'

jobs:
    lint-python:
        name: "Lint (flake8)"
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'
                  architecture: 'x64'
            - name: List current working dir (debug)
              run: ls -la
            - name: Install Python Dependencies (poetry)
              run: |
                  python -m pip install --upgrade pip
                  curl -sSL https://install.python-poetry.org | python -
                  source $HOME/.poetry/env
                  poetry install
            # - name: Check Formatting (black)
            #   run: black --line-length 120 aws_account
            - name: Lint (flake8)
              run: |
                source $HOME/.poetry/env
                poetry run flake8 --max-line-length 120 aws_account
